<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center"><? echo $room->name ?></h1>
         
        </div>
        <?
        foreach($room->getUser(['conditions' => 'room_room_id = '.$room->room_id]) as $item){
        if($item->role='manager'){
                echo Phalcon\Tag::linkTo(
                    [
                        "room/edit/".$room->room_id,
                        'Редактировать',
                        "class" => "btn btn-primary",
                    ]
                );
              }}
              ?>
      </div>
    </div>
  </div>

<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h3>Сообщения</h3>
          <ul class="list-group list-group-flush" style="max-height: 45vh; overflow: auto;">
             
            
                <?  foreach ($room->getMessage(['conditions' => 'room_room_id = '.$room->room_id]) as $message) {
                        
                        $item = $message->getUser();
                        $username = $item->second_name . ' ' . $item->name;
                        ?>
                        <li class="list-group-item">
                          <? echo $username.'<br>';
                             echo $message->text.'<br>';
                             echo $message->date_time;
                             ?>
                        </li><?
                    }
                ?>
                
          </ul>
          <div class="card card-footer">
                    <?php echo $this->tag->form(["message/create", "method" => 'POST', "class" => 'form-inline']); ?>
                    <?php echo $this->tag->textArea(["text", "class" => 'w-100', "rows" => '3']); ?>
                    <?php echo $this->tag->hiddenField(['room_id', "value" => $room->room_id]); ?>
                    <?php echo $this->tag->hiddenField(['user_id', "value" => $this->session->get('auth')['id']]); ?>
                    <?php echo $this->tag->submitButton(['Отправить', "class" => "btn btn-success w-100"]); ?>
                    </form>
                
            </div>
        </div>
        <div class="col-md-6">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe src="https://www.youtube.com/embed/ctvlUvN6wSE?controls=0" allowfullscreen="" class="embed-responsive-item"></iframe>
          </div>
        </div>
        <div class="col-md-3">
          <h3>Список выступающих</h3>
          <ul class="list-group list-group-flush" style="max-height: 50vh; overflow: auto;">
            
              <? 

              foreach ($room->getUser(['conditions' => 'room_room_id = '.$room->room_id]) as $item){
                 $username = $item->second_name . ' ' . $item->name;
                ?>
              <li class="list-group-item">
                <?
              echo  $username;

              ?>
                

              </li><?}?>
           
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="py-2" >
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <h3>Описание</h3>
          <p><? echo $room->description ?></p>
        </div>
        <div class="col-md-3">
           <h3>Дата создания</h3> <p><?echo $room->date_time ?> </p>
         </div>
      </div>
    </div>
  </div>