<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <? if($type=='conference')
          echo '<h1 class="h1 text-center">Поиск конференции</h1>';
            elseif($type=='talks')
            echo '<h1 class="h1 text-center">Поиск переговоров</h1>';
          ?>
        </div>
      </div>
    </div>
</div>
<div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <?php
            echo $this->tag->form(
                [
                    "room/result/".$type,
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
            <div class="form-group">
                <label for="fieldName" class="control-label">Название конмнаты</label>
                <div >
                    <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldDate" class="control-label">Дата создания</label>
                <div>
                    
                    <?php echo $this->tag->dateField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
                </div>
            </div>

            <?php echo $this->tag->hiddenField(
                [
                    "type", 
                    "value" => $type,
                ]
            )?>
            

            
            

            <div class="form-group">
                <div>
                    <?php echo $this->tag->submitButton(["Поиск", "class" => "btn btn-default"]) ?>
                </div>
            </div>
            </div>
        <?php echo $this->tag->endForm(); ?>
        </div>
    
</div>
</div>
</div>
