<?php use Phalcon\Tag; ?>
<div class="py-2">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
         <h1 class="h1 text-center">Список выступающих</h1>
      </div>
    </div>
  </div>
</div>


<div class="py-2">
  <div class="container">
    <div class="row">
      <div class="col-md-12 my-2">
        <?
            echo Phalcon\Tag::linkTo(
              [
                "user/search/".$room->room_id,
                'Поиск пользователя',
                "class" => "btn btn-primary",
              ]
            );?>
      </div>
      <div class="col-md-12">
        <?php echo $this->getContent(); ?>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Email</th>
                <th>Фамилия</th>
                <th>Имя</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($page as $user){ ?>
                <tr>
                  <td><?php echo $user->email ?></td>
                  <td><?php echo $user->second_name ?></td>
                  <td><?php echo $user->name ?></td>
                  <td><?php echo $this->tag->linkTo(["user/delete/" . $user->user_id, "Удалить"]); ?></td>
                </tr>
              <?php } ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
