<?php use Phalcon\Tag; ?>
<div class="py-2">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
         <h1 class="h1 text-center">Список выступающих</h1>
      </div>
    </div>
  </div>
</div>


<div class="py-2">
  <div class="container">
    <div class="row">
      <div class="col-md-12 my-2">
        <?
             echo Phalcon\Tag::linkTo(
                    [
                        "user/search/".$room->room_id,
                        'Поиск пользователей',
                        "class" => "btn btn-primary",
                    ]
                );?>
      </div>
      <div class="col-md-12">
        <?php echo $this->getContent(); ?>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Email</th>
                <th>Фамилия</th>
                <th>Имя</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <? 
              if($room!=null)
              foreach ($room->getUser(['conditions' => 'room_room_id = '.$room->room_id.' and role = "speaker"']) as $item){?>
                <tr>
                  <td><?php echo $item->email ?></td>
                  <td><?php echo $item->second_name ?></td>
                  <td><?php echo $item->name ?></td>
                  <td><?php echo $this->tag->linkTo(["user/delete/" . $room->room_id.'/'. $item->user_id, "Удалить"]); ?></td>
                </tr>

              <?php } ?>
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
