<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Список выступающих</h1>
        </div>
      </div>
    </div>
  </div>
<div>
<?
   echo Phalcon\Tag::linkTo(
                    [
                        "user/search",
                        'Поиск пользователя',
                        "class" => "btn btn-primary",
                    ]
                );?>
</div>