<div class="py-5 text-center" style="background-image: url('/diplom/public/img/fon.jpg');background-size:cover; height: 68.6%" >
    <div class="container ">
      <div class="row my-5">
        <div class="bg-white p-5 mx-auto col-md-8 col-10">
          <h4><b>CONFERENCE</b></h4>
          <p class="mb-4">Данная система направлена на проведение переговоров и конференций, а также отображения статистики их проведения.</p>
        </div>
      </div>
    </div>
  </div>