<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Поиск переговоров</h1>
        </div>
      </div>
    </div>
</div>
<div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <?php
            echo $this->tag->form(
                [
                    "talks/search",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
            <div class="form-group">
                <label for="fieldName" class="control-label">Название конмнаты</label>
                <div >
                    <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldDate" class="control-label">Дата создания</label>
                <div>
                    
                    <?php echo $this->tag->dateField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
                </div>
            </div>

            <?php echo $this->tag->hiddenField(
                [
                    "type", 
                    "value" => "talks",
                ]
            )?>
            

            
            

            <div class="form-group">
                <div>
                    <?php echo $this->tag->submitButton(["Поиск", "class" => "btn btn-default"]) ?>
                </div>
            </div>
            </div>
        <?php echo $this->tag->endForm(); ?>
        </div>
    
<div class="col-md-12">

<div class="page-header">
    <h1>Результаты поиска</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="col-md-9">
          <div class="list-group">
            <?php 
              
                  foreach ($page->items as $item)
                  { 
            echo $this->tag->linkTo( 
              [
                "room/index/".$item->room_id,
                " <div class='d-flex w-100 justify-content-between'>
                <h5 class='mb-1'>".$item->name."</h5>
                <smal>".$item->date."</smal>
              </div>
              <div class='d-flex w-100 justify-content-between'>
                <p class='mb-1'>".$item->description."</p>
              </div>",
              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",
            ]
            );} ?>
          </div>
        </div>
</div>
</div>
</div>
</div>
</div>