<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Конференции</h1>
        </div>
      </div>
    </div>
  </div>
  

  <div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <?
            echo $this->tag->linkTo( 
                [
                  "",
                  '<i class="fa fa-plus text-primary mr-2" aria-hidden="true"></i> Создание комнаты',
                  'class' => 'list-group-item list-group-item-action',
                  'data-toggle' => 'modal',
                  'data-target' => '#createConference'
                ]
              );
            ?>
            <?
            echo $this->tag->linkTo( 
                [
                  "conference/search",
                  '<i class="fa fa-search text-primary mr-2" aria-hidden="true"></i> Поиск комнаты',
                  'class' => 'list-group-item list-group-item-action',
                ]
              );
            ?>
            
          </div>
        </div>
        <div class="col-md-9">
          <div class="list-group">
            <?php 
              
                  foreach ($page->items as $item)
                  { 
            echo $this->tag->linkTo( 
              [
                "room/index/".$item->room_id,
                " <div class='d-flex w-100 justify-content-between'>
                <h5 class='mb-1'>".$item->name."</h5>
                <smal>".$item->date_time."</smal>
              </div>
              <div class='d-flex w-100 justify-content-between'>
                <p class='mb-1'>".$item->description."</p>
              </div>",
              "class" => "list-group-item list-group-item-action flex-column align-items-start btn-outline-primary",
            ]
            );} ?>
          </div>
        </div>
      </div>
      
    </div>
  </div>

  <div class="modal fade" id="createConference">
  <div class="modal-dialog " role="document">
    
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Создать комнату</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <?php 
            $role=$this->session->auth['role'];
            if($role != 'guest' && $role != null){
              ?>
        <?echo Phalcon\Tag::form(
            [
                "conference/create",
                "method" => "post",
                "class"=>"form-horizontal",
            ]
        );?>
        <div class="form-group">
          <label for="nameInput">Наименование</label>
          <input type="text" name="name" class="form-control" id="nameInput">
        </div>
        <div class="form-group">
          <label for="descriptionInput">Описание</label>
          <textarea type="text" name="description" class="form-control" id="descriptionInput"></textarea>
        </div>
        <div class="form-group">
          <button type="submit" style="width:100%" class="btn btn-outline-primary">Создать комнату</button>
        </div>
        </form>
        <? }else{?>
    <h5>Авторизируйтесь для создания комнаты</h5>
    <?}?>
      </div>
      
    </div><!-- /.модальное окно-Содержание -->

  </div><!-- /.модальное окно-диалог -->
</div>