<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Поиск пользователя</h1>
        </div>
      </div>
    </div>
</div>
<div>
    <div class="container">
      <div class="row">
        <?php echo $this->getContent(); ?>
        <div class="col-md-12">
        <?php
            echo $this->tag->form(
                [
                    "user/search/".$room->room_id,
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
            <div class="form-group">
                <label for="fieldEmail" class="control-label">Email</label>
                <div >
                    <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldName" class="control-label">Имя</label>
                <div>
                    <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
                </div>
            </div>

            <div class="form-group">
                <label for="fieldSecondName" class="control-label">Фамилия</label>
                <div>
                    <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("room_id") ?>
            <div class="form-group">
                <div>
                    <?php echo $this->tag->submitButton(["Поиск", "class" => "btn btn-default"]) ?>
                </div>
            </div>
        <?php echo $this->tag->endForm(); ?>
        </div>
    
<div class="col-md-12">

<div class="page-header">
    <h1>Результаты поиска</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Email</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->second_name ?></td>
            <td><?php echo $user->name ?></td>
            <td><?php echo $this->tag->linkTo(["room/add/" . $user->user_id."/".$room->room_id, "Добавить"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
</div>
</div>
</div>
</div>