<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Поиск пользователя</h1>
        </div>
      </div>
    </div>
  </div>
<div class="py-5" >
    <div class="container">
        <?php echo $this->getContent(); ?>
      <div class="row">

<?php
    echo $this->tag->form(
        [
            "user/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>
<div class="form-group">
    <label for="fieldEmail" class="control-label">Email</label>
    <div >
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="control-label">Имя</label>
    <div>
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSecondName" class="control-label">Фамилия</label>
    <div>
        <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
    </div>
</div>


<div class="form-group">
    <div>
        <?php echo $this->tag->submitButton(["Поиск", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
</div></div></div>