<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Персональные настройки</h1>
        </div>
      </div>
    </div>
  </div>

<!--//форма изменения пароля-->
<div class="py-5" >
    <div class="container">
        <?php echo $this->getContent(); ?>
      <div class="row">
<?php
    echo $this->tag->form(
        [
            "user/save",
            "autocomplete" => "off",
            "class" => "form-horizontal w-100"
        ]
    );
?>
    <div class="form-group">
        <label for="fieldPass" class="control-label">Старый пароль</label>
        <div>
            <?php echo $this->tag->passwordField(["old_pass", "size" => 30, "class" => "form-control", "id" => "fieldPass"]) ?>
        </div>
    </div>
    <div class="form-group">
        <label for="fieldPass" class="control-label">Новый пароль</label>
        <div>
            <?php echo $this->tag->passwordField(["pass",  "size" => 30, "class" => "form-control", "id" => "fieldPass"]) ?>
        </div>
    </div>
    <div class="form-group">
        <label for="fieldPass" class="control-label">Повторите пароль</label>
        <div>
            <?php echo $this->tag->passwordField(["re_pass",  "size" => 30, "class" => "form-control", "id" => "fieldPass"]) ?>
        </div>
    </div>

    <div class="form-group">
        <div>
            <?php echo $this->tag->submitButton(["Изменить пароль", "class" => "btn btn-success"]) ?>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>


<!--//форма изменения личных данных-->
<?php
    echo $this->tag->form(
        [
            "user/save",
            "autocomplete" => "off",
            "class" => "form-horizontal w-100"
        ]
    );
?>

<div class="form-group">
    <label for="fieldEmail" class="control-label">Email</label>
    <div>
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="control-label">Имя</label>
    <div>
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSecondName" class="control-label">Фамилия</label>
    <div>
        <?php echo $this->tag->textField(["second_name", "size" => 30, "class" => "form-control", "id" => "fieldSecondName"]) ?>
    </div>
</div>

<?php echo $this->tag->hiddenField("user_id") ?>

<div class="form-group">
    <div>
        <?php echo $this->tag->submitButton(["Сохранить личные данные", "class" => "btn btn-success"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
</div>
</div>
</div>
