<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Статистика</h1>
        </div>
      </div>
    </div>
  </div>
  
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <b >Выберете тип комнат:</b>
           <?php
            echo $this->tag->form(
                [
                    "statistic/index",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>
          <div class="btn-group my-2">
            
              <?
              echo $this->tag->selectStatic( 
                [ 
                  "type", 
                  [ 
                    ""            => "Не выбрано", 
                    "conference"  => "Конференции", 
                    "talks"       => "Переговоры", 
                  ] , "class"=>"btn btn-primary"
                ] 
              );
              ?>

            </div>

          <hr>
          <div>
            <b class="my-2">Выберете период для построения графика</b>

            <p class="my-1">Начало:</p>
             <?php echo $this->tag->dateField(["date1", "class" => "form-control my-2", "id" => "fieldDate1"]) ?>
          </div>
          <div>
            <p class="my-1">Конец:</p>
             <?php echo $this->tag->dateField(["date2", "class" => "form-control my-2", "id" => "fieldDate2"]) ?>
          </div>
          <hr>
          <div>
            <?php echo $this->tag->submitButton(["Построить", "class" => "btn btn-primary my-2"]) ?>
          </div>
           <?php echo $this->tag->endForm(); ?>
        </div>
        <div class="col-md-9">
          <div class="col-md-12" >
            <?php echo $this->getContent(); 
            echo "Количество комнат за данный период: ".count($room);
            ?>
            <div id="chart_div" class="text-center">График загружается</div>
            <?php echo $this->getContent(); 
            echo "Количество гостей за данный период: ".$summ;
            ?>
            <div id="chart_div2" class="text-center">График загружается</div>
          </div>
        </div>
      </div>
    </div>
  </div>

 
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
    google.charts.load("current", {packages:['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = new google.visualization.DataTable();
        data.addColumn('string', 'Дата');
    data.addColumn('number', 'Комнат');
    data.addRows([
          <?
          foreach($gr as $item) {
                  echo "['".$item[0]."' , ".$item[1]." ],\n";
          }
          ?>
      ]);
      var data2 = new google.visualization.DataTable();
        data2.addColumn('string', 'Дата');
    data2.addColumn('number', 'Гостей');
    data2.addRows([
          <?
          foreach($gu as $item) {
                  echo "['".$item[0]."' , ".$item[1]." ],\n";
          }
          ?>
      ]);
      var options = {
        title: "Количество созданных комнат к дате",
        width: 600,
        height: 400,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
      };
      var options2 = {
        title: "Количество гостей комнат к дате",
        width: 600,
        height: 400,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("chart_div"));
      chart.draw(data, options);
      var chart2 = new google.visualization.ColumnChart(document.getElementById("chart_div2"));
      chart2.draw(data2, options2);
  }
  </script>

 