<div class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="h1 text-center">Статистика</h1>
        </div>
      </div>
    </div>
  </div>
  
<div class="py-5" >
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <b >Выберете тип комнат:</b>
          <div class="btn-group my-2">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Выберете тип </button>
            <div class="dropdown-menu"> <a class="dropdown-item" href="#">Конференции</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Переговоры</a>
            </div>

          </div>
          <hr>
          <div>
            <b class="my-2">Выберете период для построения графика</b>

            <p class="my-1">Начало:</p>
            <input type="date" class="form-control my-2" id="date" name="date" placeholder="Дата" required="">
          </div>
          <div>
            <p class="my-1">Конец:</p>
            <input type="date" class="form-control my-2" id="date" name="date" placeholder="Дата" required="">
          </div>
          <hr>
          <div>
            <a class="btn btn-primary my-2" href="#">Построить</a>
          </div>
        </div>
        <div class="col-md-9">
          <div class="col-md-12" ><img class="img-fluid d-block mx-auto" src="https://static.pingendo.com/img-placeholder-1.svg"></div>
        </div>
      </div>
    </div>
  </div>

 